### PR TITLE
Bump io-classes

### PR DESCRIPTION
**Pull request by bolt12**
CHaP revision: 

- https://github.com/IntersectMBO/cardano-haskell-packages/pull/768
- https://github.com/IntersectMBO/cardano-haskell-packages/pull/769

### CODE REVIEW

**Review by lehins — APPROVED** [review]
:+1:

**Comment by bolt12** [comment]
Any idea why the CI is failing for that particular machine? @lehins

**Comment by lehins** [comment]
> Any idea why the CI is failing for that particular machine?

Honestly, I have no clue. Could be some sort of new MacOS and some crypto dependency and ghc-8.10 incompatibility.

I don't have a mac to reproduce it unfortunately.

Maybe @angerman could assist us with this. He is a true guru of this sort of stuff.

**Comment by lehins** [comment]
> Any idea why the CI is failing for that particular machine? @lehins

@bolt12 The problem is that ghc-8 is not supported on latest MacOS. Which I learned earlier this month from reviewing this PR: https://github.com/haskell/vector/pull/493 except I forgot about it and it just dawned on me today that this is the issue we are seeing here in cardano-base. 
Could you please give #478 PR a review and revert a commit that adds LLVM to CI

**Pull request merged**
