### PR TITLE
Update `CHANGELOG`s post-release 

### PR DESCRIPTION
**Pull request by Lucsanszky**
Update `CHANGELOG`s where relevant and also fix some inaccuracies in `RELEASING.md`.

### CODE REVIEW

**Review by lehins — APPROVED** [review]
Perfect! You got the git tags for the released packages too. Very nice job!

**Comment by Lucsanszky** [comment]
> Perfect! You got the git tags for the released packages too. Very nice job!

Cheers! I've just realised that I also have to update the `flake.lock` file to make sure that CHaP is up-to-date, right?

**Comment by lehins** [comment]
>  I also have to update the flake.lock file to make sure that CHaP is up-to-date, right?

Nope, not in cardano-base, because regardless what is on CHaPs, this repo will use `cardano-slotting` and `strict-containers` from this repo.

It is the `index-state` and `flake.nix` need to be updated in ledger repo.

**Comment by Lucsanszky** [comment]
> > I also have to update the flake.lock file to make sure that CHaP is up-to-date, right?
> 
> Nope, not in cardano-base, because regardless what is on CHaPs, this repo will use `cardano-slotting` and `strict-containers` from this repo.
> 
> It is the `index-state` and `flake.nix` need to be updated in ledger repo.

Ah okay, makes sense. Thanks for clarifying!

**Pull request merged**
